package com.github.lyokofirelyte.Elysian.MMO;

public enum MMO {

	IS_TREE_FELLING("IS_TREE_FELLING"),
	TREE_FELLER_CD("TREE_FELLER_CD"),
	IS_SUPER_BREAKING("IS_SUPER_BREAKING"),
	SUPER_BREAKER_CD("SUPER_BREAKER_CD"),
	IS_SKY_BLADING("IS_SKY_BLADING"),
	SKY_BLADE_CD("SKY_BLADE_CD"),
	SKY_BLADE_COUNTER("SKY_BLADE_COUNTER"),
	SAVED_ENCHANTS("SAVED_ENCHANTS"),
	IS_CHOPPING("IS_CHOPPING"),
	IS_BLADING("IS_BLADING"),
	IS_MINING("IS_MINING");
	
	MMO(String type){
		this.type = type;
	}
	
	public String type;
}